import { type PageRecordConfig } from './types';

export const PAGES: PageRecordConfig[] = [
  {
    id: 'quickstart',
    name: 'Quickstart',
    filename: 'MSPY-angular-01-Quickstart',
    docUrl: 'https://docs.copilotkit.ai/angular/ms-agent-python/quickstart',
    ideFile: 'frontend/src/app/features/quickstart/quickstart-chat.ts',
    startLine: 1,
    endLine: 16,
    demoUrl: 'http://localhost:4200/quickstart/demo',
    prompt: 'Can you tell me a joke?',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'chat-ui',
    name: 'Chat UI & Customization',
    filename: 'MSPY-angular-02-ChatUi',
    docUrl: 'https://docs.copilotkit.ai/angular/ms-agent-python/guides/chat-ui',
    ideFile: 'frontend/src/app/features/chat-ui/chat-ui-demo.component.ts',
    startLine: 28,
    endLine: 110,
    demoUrl: 'http://localhost:4200/chat-ui/demo',
    prompt: 'What is CopilotKit?',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'frontend-tools-generative-ui',
    name: 'Frontend Tools & Generative UI',
    filename: 'MSPY-angular-03-FrontendToolsGenUI',
    docUrl: 'https://docs.copilotkit.ai/angular/ms-agent-python/guides/frontend-tools-generative-ui',
    ideFile: 'frontend/src/app/features/tools/tools-chat.component.ts',
    startLine: 22,
    endLine: 66,
    demoUrl: 'http://localhost:4200/frontend-tools-generative-ui/demo',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 8000,
  },
  {
    id: 'a2ui',
    name: 'A2UI Schemas, Styling & Recovery',
    filename: 'MSPY-angular-04-A2UI',
    docUrl: 'https://docs.copilotkit.ai/angular/ms-agent-python/guides/a2ui',
    ideFile: 'frontend/src/app/features/a2ui/a2ui-chat.component.ts',
    startLine: 12,
    endLine: 25,
    demoUrl: 'http://localhost:4200/a2ui/demo',
    prompt: 'Show me a card comparing two flight options.',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'voice-multimodal',
    name: 'Voice & Multimodal Input',
    filename: 'MSPY-angular-05-VoiceMultimodal',
    docUrl: 'https://docs.copilotkit.ai/angular/ms-agent-python/guides/voice-multimodal',
    ideFile: 'frontend/src/app/features/media/voice-chat.component.ts',
    startLine: 13,
    endLine: 32,
    demoUrl: 'http://localhost:4200/voice-multimodal/demo',
    prompt: 'Tell me what you can do with images and voice',
    waitAfterPromptMs: 7000,
  },
  {
    id: 'human-in-the-loop',
    name: 'Human-In-The-Loop & Interrupts',
    filename: 'MSPY-angular-06-HumanInTheLoop',
    docUrl: 'https://docs.copilotkit.ai/angular/ms-agent-python/guides/human-in-the-loop',
    ideFile: 'frontend/src/app/features/hitl/approval-card.component.ts',
    startLine: 18,
    endLine: 42,
    demoUrl: 'http://localhost:4200/human-in-the-loop/demo',
    prompt: 'Delete my account, but ask me to approve it first.',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'shared-state',
    name: 'Shared State & Agent Context',
    filename: 'MSPY-angular-07-SharedState',
    docUrl: 'https://docs.copilotkit.ai/angular/ms-agent-python/guides/shared-state',
    ideFile: 'frontend/src/app/features/shared-state/workspace.component.ts',
    startLine: 21,
    endLine: 51,
    demoUrl: 'http://localhost:4200/shared-state/demo',
    prompt: 'What is my current priority and what notes do I have?',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'threads',
    name: 'Threads & Multi-Turn Conversations',
    filename: 'MSPY-angular-08-Threads',
    docUrl: 'https://docs.copilotkit.ai/angular/ms-agent-python/guides/threads-memory-attachments-headless',
    ideFile: 'frontend/src/app/features/threads/threads-demo.component.ts',
    startLine: 10,
    endLine: 35,
    demoUrl: 'http://localhost:4200/threads/demo',
    prompt: 'Hello from thread management demo!',
    waitAfterPromptMs: 7000,
  },
  {
    id: 'memory',
    name: 'Memory & State Persistence',
    filename: 'MSPY-angular-09-Memory',
    docUrl: 'https://docs.copilotkit.ai/angular/ms-agent-python/guides/threads-memory-attachments-headless',
    ideFile: 'frontend/src/app/features/memory/memory-demo.component.ts',
    startLine: 10,
    endLine: 30,
    demoUrl: 'http://localhost:4200/memory/demo',
    prompt: 'Remember that I am working on an Angular 22 project',
    waitAfterPromptMs: 7000,
  },
  {
    id: 'attachments',
    name: 'Attachments & File Uploads',
    filename: 'MSPY-angular-10-Attachments',
    docUrl: 'https://docs.copilotkit.ai/angular/ms-agent-python/guides/threads-memory-attachments-headless',
    ideFile: 'frontend/src/app/features/attachments/media-chat.component.ts',
    startLine: 8,
    endLine: 28,
    demoUrl: 'http://localhost:4200/attachments/demo',
    prompt: 'What types of attachments are supported?',
    waitAfterPromptMs: 7000,
  },
  {
    id: 'headless',
    name: 'Headless UI & Custom Composer',
    filename: 'MSPY-angular-11-HeadlessUI',
    docUrl: 'https://docs.copilotkit.ai/angular/ms-agent-python/guides/threads-memory-attachments-headless',
    ideFile: 'frontend/src/app/features/headless/headless-chat.component.ts',
    startLine: 12,
    endLine: 66,
    demoUrl: 'http://localhost:4200/headless/demo',
    prompt: 'Tell me a short joke about Angular',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'copilot-runtime',
    name: 'Copilot Runtime (Node.js)',
    filename: 'MSPY-angular-12-CopilotRuntime',
    docUrl: 'https://docs.copilotkit.ai/angular/ms-agent-python',
    ideFile: 'frontend/server.ts',
    startLine: 24,
    endLine: 61,
    demoUrl: 'http://localhost:4200/quickstart/demo',
    prompt: 'How does Copilot Runtime bridge Angular to Python?',
    waitAfterPromptMs: 7000,
  },
  {
    id: 'backend-agent',
    name: 'Backend - Microsoft Agent Framework (FastAPI)',
    filename: 'MSPY-angular-13-BackendAgent',
    docUrl: 'https://docs.copilotkit.ai/angular/ms-agent-python',
    ideFile: 'backend/main.py',
    startLine: 74,
    endLine: 111,
    demoUrl: 'http://localhost:4200/quickstart/demo',
    prompt: 'What tools are configured in the Python backend?',
    waitAfterPromptMs: 7000,
  },
];
